#!/bin/sh
#
# Clear the /tmp directory.
#

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

# Special case for /tmp/run, which might contain Docker secrets or sockets
# (e.g. docker.sock bind-mounted via /var/run -> /tmp/run symlink).
if [ -d /tmp/run ]; then
    if df /tmp/run/secrets >/dev/null 2>/dev/null; then
        find /tmp/run -mindepth 1 -maxdepth 1 ! -name 'secrets' -exec rm -rf {} +
    else
        # Remove items individually; ignore failures for busy bind-mounts (e.g. docker.sock).
        find /tmp/run -mindepth 1 -maxdepth 1 -exec rm -rf {} + 2>/dev/null || true
        # Only succeeds when the directory is truly empty; silently ignored otherwise.
        rmdir /tmp/run 2>/dev/null || true
    fi
fi

# Remove everything, except:
#   - /tmp/.cont-env-internal: this file has been generated by the init script.
#   - /tmp/run: this directory has been handled previously.
find /tmp -mindepth 1 -maxdepth 1 ! -name '.cont-env-internal' ! -name 'run' -exec rm -rf {} +

# vim:ft=sh:ts=4:sw=4:et:sts=4
